(() => {
  'use strict';
  const REPO = 'howaboutj/howaboutj.github.io', BRANCH = 'main';
  const paths = {people:'people/index.html', publications:'publications/index.html', news:'news/index.html', 'lab-life':'lab-life/index.html'};
  const $ = (s,root=document) => root.querySelector(s);
  let token = '', page = 'people', source = '', sha = '', doc = null, selected = null, pending = null, user = '';
  const status = (message,error=false) => { $('#status').textContent=message; $('#status').classList.toggle('error',error); };
  const safe = x => String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const decode = s => new TextDecoder().decode(Uint8Array.from(atob(s.replace(/\s/g,'')),c=>c.charCodeAt(0)));
  const encode = s => {const bytes=new TextEncoder().encode(s);let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out);};
  async function api(path, options={}) {
    const response = await fetch(`https://api.github.com${path}`, { ...options, headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,'X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})} });
    const body = await response.json().catch(()=>({}));
    if (!response.ok) throw new Error(body.message||`GitHub HTTP ${response.status}`);
    return body;
  }
  const contentPath = p => `/repos/${REPO}/contents/${p}`;
  const children = (parent, selector) => [...parent.children].filter(x=>x.matches(selector));
  function sections() {return [...doc.querySelectorAll('main section')].filter(s=>s.querySelector(':scope > h2') && s.querySelector(':scope > div'))}
  function grid(section){return section.querySelector(':scope > div')}
  function list(){if(page==='people')return sections().flatMap(s=>children(grid(s),'div').map(node=>({node,section:s.querySelector('h2').textContent.trim()})));
    if(page==='publications')return [...doc.querySelectorAll('li[data-pub]')].map(node=>({node}));
    return [...doc.querySelectorAll('main article')].map(node=>({node}));}
  function galleryScript(){return [...doc.querySelectorAll('script')].find(s=>s.textContent.includes('const lightboxData ='))}
  function gallery(){const s=galleryScript();const m=s&&s.textContent.match(/const lightboxData\s*=\s*(\[[\s\S]*?\]);/);if(!m)throw Error('사진 목록 데이터를 찾지 못했습니다.');return JSON.parse(m[1]);}
  function setGallery(items){const s=galleryScript();s.textContent=s.textContent.replace(/const lightboxData\s*=\s*\[[\s\S]*?\];/,()=> 'const lightboxData = '+JSON.stringify(items)+';');}
  function data(item){const n=item.node;
    if(page==='people'){const trigger=$('[data-person-trigger]',n)||$('a',n);return {name:trigger?.dataset.name||$('h3',n)?.textContent.trim()||'',section:item.section,role:trigger?.dataset.role||$('p',n)?.textContent.trim()||'',title:trigger?.dataset.title||'',email:trigger?.dataset.email||'',photo:trigger?.dataset.photo||$('img',n)?.getAttribute('src')||'',affiliation:$('.alumni-affiliation',n)?.textContent.trim()||''};}
    if(page==='publications')return {title:$('p',n)?.textContent.trim()||'',citation:$('p + p',n)?.textContent.trim()||'',type:n.dataset.pubType||'',year:n.dataset.pubYear||''};
    const index=page==='lab-life'?Number(n.querySelector('[data-item-index]')?.dataset.itemIndex):-1;
    const g=page==='lab-life'?gallery()[index]:null;
    return {title:$('h3',n)?.textContent.trim()||'',date:$('p.text-sm',n)?.textContent.trim()||'',description:page==='lab-life'?($('h3 + p',n)?.textContent.trim()||''):'',photo:g?.images?.[0]||$('[data-lightbox]',n)?.dataset.full||$('img',n)?.getAttribute('src')||'',photos:g?.images?.join('\n')||[...n.querySelectorAll('[data-lightbox]')].map(b=>b.dataset.full).join('\n'),index};
  }
  function render(){const q=$('#search').value.toLowerCase().trim();const items=list().filter(x=>!q||JSON.stringify(data(x)).toLowerCase().includes(q));$('#count').textContent=`${items.length}개 항목`;
    $('#items').replaceChildren(...items.map(item=>{const d=data(item);const row=document.createElement('div');row.className='item';const image=document.createElement('img');image.src=d.photo||'';image.alt='';image.onerror=()=>image.removeAttribute('src');const body=document.createElement('div');body.innerHTML=`<strong>${safe(d.name||d.title)}</strong><small>${safe(d.section||d.type||d.date)} ${safe(d.role||d.year||'')}</small>`;const actions=document.createElement('div');actions.className='actions';for(const [label,fn,cls] of [['수정',()=>form(item)],['↑',()=>move(item,-1)],['↓',()=>move(item,1)],['삭제',()=>remove(item),'danger']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=cls||'';b.onclick=fn;actions.append(b)}row.append(image,body,actions);return row}));}
  const types=['International Journal','Domestic Journal','International Conference','Domestic Conference','Patent'];
  function fields(){if(page==='people')return [{key:'name',label:'이름',required:true},{key:'section',label:'섹션',options:sections().map(s=>s.querySelector('h2').textContent.trim())},{key:'role',label:'직책 / 학위'},{key:'title',label:'연구 분야 / 상세 정보'},{key:'email',label:'이메일'},{key:'affiliation',label:'졸업생 소속'},{key:'photo',label:'사진 주소',placeholder:'/_astro/... 또는 업로드'}];
    if(page==='publications')return [{key:'title',label:'논문 제목',required:true},{key:'citation',label:'서지 정보',multiline:true,required:true},{key:'type',label:'분류',options:types},{key:'year',label:'연도',required:true}];
    if(page==='news')return [{key:'title',label:'제목',required:true},{key:'date',label:'게시 날짜',required:true,placeholder:'October 6, 2026'},{key:'photos',label:'사진 주소 (한 줄에 하나)',multiline:true}];
    return [{key:'title',label:'제목',required:true},{key:'date',label:'게시 날짜',required:true},{key:'description',label:'본문',multiline:true},{key:'photos',label:'사진 주소 (한 줄에 하나)',multiline:true,placeholder:'/_astro/photo-1.jpg'}];}
  function form(item=null){selected=item;pending=null;const d=item?data(item):{};$('#form-title').textContent=item?'항목 수정':'새 항목 추가';$('#fields').replaceChildren(...fields().map(f=>{const label=document.createElement('label');label.textContent=f.label;let control;if(f.options){control=document.createElement('select');for(const opt of f.options){const o=document.createElement('option');o.value=o.textContent=opt;control.append(o)}}else{control=document.createElement(f.multiline?'textarea':'input');if(!f.multiline)control.type='text';control.placeholder=f.placeholder||''}control.name=f.key;control.value=d[f.key]||'';control.required=!!f.required;label.append(control);return label}));
    if(page!=='publications'){const label=document.createElement('label');label.textContent=page==='lab-life'?'새 사진 파일 (여러 장 가능)':'새 사진 파일';const input=document.createElement('input');input.type='file';input.accept='image/jpeg,image/png,image/webp,image/gif';input.multiple=page==='lab-life'||page==='news';input.onchange=()=>{pending=[...input.files];status(`${pending.length}개 파일은 저장을 누르면 업로드됩니다.`)};label.append(input);$('#fields').append(label)}$('#form-area').hidden=false;$('#form-area').scrollIntoView({behavior:'smooth',block:'start'});}
  function personCard(d){const wrap=doc.createElement('div');wrap.className='text-center';wrap.innerHTML=`<button type="button" data-person-trigger class="group block w-full text-center"><div class="mx-auto h-32 w-32 overflow-hidden rounded-full ring-1 ring-slate-200 transition duration-300 group-hover:shadow-md group-hover:ring-2 group-hover:ring-primary-300"><img class="h-full w-full object-cover" loading="lazy" alt=""></div><h3 class="mt-3 font-serif text-base text-slate-900 group-hover:text-primary-700"></h3><p class="text-sm text-slate-600"></p></button>`;return wrap;}
  function updatePerson(node,d){const t=$('[data-person-trigger]',node)||$('a',node);if(t.matches('[data-person-trigger]')){for(const k of ['name','role','title','email'])t.dataset[k]=d[k]||'';t.dataset.photo=d.photo||'';t.dataset.initials=(d.name||'').split(/\s+/).map(x=>x[0]).join('').slice(0,3)}$('h3',node).textContent=d.name;let role=$('p:not(.alumni-affiliation)',node);if(!role){role=doc.createElement('p');role.className='text-sm text-slate-600';$('h3',node).after(role)}role.textContent=d.section==='Alumni'?(d.role||''):d.role||'';let aff=$('.alumni-affiliation',node);if(d.section==='Alumni'&&d.affiliation){if(!aff){aff=doc.createElement('p');aff.className='alumni-affiliation mt-1 text-xs text-slate-500';role.after(aff)}aff.textContent=d.affiliation}else aff?.remove();const im=$('img',node);if(im){im.src=d.photo||'';im.removeAttribute('srcset');im.alt=d.name}}
  function pubCard(){const li=doc.createElement('li');li.className='pl-1';li.setAttribute('data-pub','');li.innerHTML='<p class="font-medium text-slate-900"></p><p class="mt-1 text-sm leading-relaxed text-slate-600"></p>';return li}
  function updatePub(node,d){node.dataset.pubType=d.type;node.dataset.pubYear=d.year;$('p',node).textContent=d.title;$('p + p',node).textContent=d.citation;}
  function articleCard(){const a=doc.createElement('article');a.className=page==='news'?'grid gap-5 border-b border-slate-200 pb-10 last:border-b-0 sm:grid-cols-[minmax(0,15rem)_1fr]':'grid gap-5 border-b border-slate-200 pb-8 last:border-b-0 sm:grid-cols-[9rem_1fr]';a.innerHTML='<div class="grid gap-1.5 grid-cols-1"><button type="button" class="group relative block aspect-[4/3] w-full cursor-zoom-in overflow-hidden rounded-lg border border-slate-200 bg-slate-50"><img loading="lazy" class="aspect-[4/3] w-full object-cover"></button></div><div><p class="text-sm text-slate-500"></p><h3 class="mt-1 font-serif text-lg text-slate-900"></h3></div>';return a}
  function updateArticle(node,d){const date=$('p.text-sm',node);if(date)date.textContent=d.date;const h=$('h3',node);if(h)h.textContent=d.title;const img=$('img',node);if(img){img.src=d.photo||'';img.removeAttribute('srcset');img.alt=d.title}const button=$('button',node);if(page==='news'){const photos=d.photos||[d.photo].filter(Boolean);const holder=button.parentElement;const template=button.cloneNode(true);holder.replaceChildren(...photos.map(url=>{const b=template.cloneNode(true);b.setAttribute('data-lightbox','');b.dataset.full=url;b.dataset.caption=d.title;b.dataset.date=d.date;b.setAttribute('aria-label','View full-size photo: '+d.title);const im=$('img',b);im.src=url;im.removeAttribute('srcset');im.alt=d.title;return b}))}else{button.setAttribute('data-lightbox-open','');button.dataset.itemIndex=d.index;button.setAttribute('aria-label','View photos: '+d.title);const badge=$('span',button);if(badge){if(d.photos.length>1)badge.textContent='+'+(d.photos.length-1);else badge.remove()}else if(d.photos.length>1){const span=doc.createElement('span');span.className='absolute bottom-1.5 right-1.5 rounded-full bg-slate-900/70 px-1.5 py-0.5 text-[11px] font-medium text-white';span.textContent='+'+(d.photos.length-1);button.append(span)}let description=$('h3 + p',node);if(d.description){if(!description){description=doc.createElement('p');description.className='mt-2 text-sm leading-relaxed text-slate-600';h.after(description)}description.textContent=d.description}else description?.remove()}for(const a of node.querySelectorAll('a[href*="iras.postech.ac.kr/main/bbs"]')){if(a.closest('h3'))a.replaceWith(doc.createTextNode(a.textContent));else a.remove()}}
  function articleContainer(){return doc.querySelector('main .space-y-10')||doc.querySelector('main .space-y-8')}
  function renumber(){if(page==='publications'){const all=list().map(x=>x.node),parent=all[0]?.parentElement;if(!parent)return;for(const type of types){const same=all.filter(n=>n.dataset.pubType===type);same.forEach((n,i)=>n.value=same.length-i);const b=[...doc.querySelectorAll('#pub-type-filters [data-type]')].find(x=>x.dataset.type===type);if(b)b.textContent=`${type} (${same.length})`}}
    if(page==='lab-life'){const ar=list().map(x=>x.node);ar.forEach((n,i)=>{const b=n.querySelector('[data-item-index]');if(b)b.dataset.itemIndex=i})}}
  async function upload(files){const urls=[];for(const file of files){if(!file.type.startsWith('image/'))throw Error('이미지 파일만 업로드할 수 있습니다.');if(file.size>8*1024*1024)throw Error('사진 한 장은 8 MB 이하로 선택하세요.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const name=`images/admin/${Date.now()}-${crypto.randomUUID().slice(0,8)}.${ext}`;const raw=await file.arrayBuffer();const bytes=new Uint8Array(raw);let str='';for(let i=0;i<bytes.length;i+=32768)str+=String.fromCharCode(...bytes.subarray(i,i+32768));await api(contentPath(name),{method:'PUT',body:JSON.stringify({message:`Add site image ${file.name}`,content:btoa(str),branch:BRANCH})});urls.push('/'+name)}return urls}
  async function publish(message){renumber();const result='<!DOCTYPE html>\n'+doc.documentElement.outerHTML;const response=await api(contentPath(paths[page]),{method:'PUT',body:JSON.stringify({message,content:encode(result),sha,branch:BRANCH})});sha=response.content.sha;source=result;status('저장됐습니다. GitHub Pages 배포가 끝나면 홈페이지에 반영됩니다.');render();}
  async function save(event){event.preventDefault();const btn=$('#save');btn.disabled=true;try{const d=Object.fromEntries(new FormData($('#content-form')));if(pending?.length){status('사진 업로드 중…');const urls=await upload(pending);if(page==='lab-life'||page==='news')d.photos=[d.photos||'',...urls].filter(Boolean).join('\n');else d.photo=urls[0];}
      if(page==='people'){const section=sections().find(s=>s.querySelector('h2').textContent.trim()===d.section);if(!section)throw Error('섹션을 찾지 못했습니다.');const node=selected?.node||personCard(d);updatePerson(node,d);if(!selected||selected.section!==d.section)grid(section).append(node)}
      else if(page==='publications'){const node=selected?.node||pubCard();updatePub(node,d);if(!selected){const list=doc.querySelector('[data-pub-list]')||doc.querySelector('li[data-pub]')?.parentElement;const first=[...list.querySelectorAll(':scope > li[data-pub]')].find(x=>x.dataset.pubType===d.type);first?list.insertBefore(node,first):list.append(node)}}
      else{const node=selected?.node||articleCard();if(page==='news'){d.photos=(d.photos||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!d.photos.length)throw Error('사진 주소나 업로드할 사진을 입력하세요.');d.photo=d.photos[0]}if(page==='lab-life'){const galleries=gallery(),photos=(d.photos||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean);if(!photos.length)throw Error('사진 주소나 업로드할 사진을 입력하세요.');d.photo=photos[0];d.photos=photos;const index=selected?list().findIndex(x=>x.node===node):0;if(selected)galleries[index]={images:photos,caption:d.title,date:d.date};else galleries.unshift({images:photos,caption:d.title,date:d.date});setGallery(galleries);d.index=index}updateArticle(node,d);if(!selected)articleContainer().prepend(node)}
      status('GitHub에 저장하는 중…');await publish(`Update ${page}: ${d.name||d.title}`);$('#form-area').hidden=true;selected=null;pending=null;
    }catch(e){doc=new DOMParser().parseFromString(source,'text/html');selected=null;pending=null;$('#form-area').hidden=true;render();status(e.message+' 최신 목록을 다시 확인한 뒤 재시도하세요.',true)}finally{btn.disabled=false}}
  async function remove(item){const d=data(item);if(!confirm(`“${d.name||d.title}” 항목을 삭제할까요?`))return;const backup=doc.documentElement.outerHTML;try{if(page==='lab-life'){const g=gallery();g.splice(list().findIndex(x=>x.node===item.node),1);setGallery(g)}item.node.remove();await publish(`Remove ${page}: ${d.name||d.title}`)}catch(e){doc=new DOMParser().parseFromString(backup,'text/html');status(e.message,true)}}
  async function move(item,delta){const items=list(),i=items.findIndex(x=>x.node===item.node),other=items[i+delta];if(!other)return;if(page==='people'&&other.section!==item.section)return status('섹션 간 이동은 수정에서 섹션을 선택하세요.',true);if(page==='publications'&&data(other).type!==data(item).type)return status('논문 분류 간 이동은 수정에서 분류를 선택하세요.',true);const backup=doc.documentElement.outerHTML;try{if(page==='lab-life'){const g=gallery();[g[i],g[i+delta]]=[g[i+delta],g[i]];setGallery(g)}if(delta<0)other.node.before(item.node);else other.node.after(item.node);await publish(`Reorder ${page}`)}catch(e){doc=new DOMParser().parseFromString(backup,'text/html');status(e.message,true)}}
  async function load(){status('저장소에서 최신 파일을 불러오는 중…');$('#items').replaceChildren();$('#form-area').hidden=true;const r=await api(contentPath(paths[page])+`?ref=${BRANCH}`);source=decode(r.content);sha=r.sha;doc=new DOMParser().parseFromString(source,'text/html');render();status('최신 파일을 불러왔습니다.');}
  $('#login-form').onsubmit=async e=>{e.preventDefault();token=$('#token').value.trim();try{const result=await api('/user');user=result.login;const repo=await api(`/repos/${REPO}`);if(!repo.permissions?.push)throw Error('이 저장소에 쓰기 권한이 없습니다.');$('#token').value='';$('#account').textContent=`${user} 계정 연결됨`;$('#login').hidden=true;$('#editor').hidden=false;await load()}catch(err){status(err.message,true);token=''}};
  $('#logout').onclick=()=>{token='';doc=null;source='';sha='';user='';$('#editor').hidden=true;$('#login').hidden=false;status('연결을 해제했습니다.')};
  $('#tabs').onclick=async e=>{const button=e.target.closest('[data-page]');if(!button||button.dataset.page===page)return;page=button.dataset.page;for(const b of $('#tabs').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b===button));$('#search').value='';try{await load()}catch(err){status(err.message,true)}};
  $('#search').oninput=render;$('#add').onclick=()=>form();$('#cancel').onclick=()=>{$('#form-area').hidden=true;selected=null;pending=null};$('#content-form').onsubmit=save;
})();
